name=RswitchCheck
version=1.0.0
author=Cristian lobo
maintainer=Cristian lobo
sentence=
paragraph=Libreria para verificar RswitchCheck.
category=Uncategorized
url=
architectures=esp32
dot_a_linkage=true
precompiled=true